import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";
import { AppProvider } from "@/providers";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "next-themes";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html
      lang="en"
      suppressHydrationWarning
      className={`
        ${geistSans.variable}
        ${geistMono.variable}
        h-full
        antialiased
      `}
    >

      <body
        className="
          min-h-full
          flex
          flex-col
          bg-background
          text-foreground
        "
      >

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <AppProvider>

            <TooltipProvider>

              {children}

              <Toaster
                richColors
                position="top-right"
                closeButton
                expand={false}
                toastOptions={{
                  style:{
                    fontSize:"14px",
                    borderRadius:"10px",
                  },
                }}
              />

            </TooltipProvider>

          </AppProvider>

        </ThemeProvider>

      </body>

    </html>

  );
}